[supabase]
url = "https://mleybpkcorglcgwhdzej.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sZXlicGtjb3JnbGNnd2hkemVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTQxNDksImV4cCI6MjA1ODQ5MDE0OX0.al1DKfO7MyKRjgC93qCnVJChh1EXVH4h61nk7AcoMFs"
